"""empty message

Revision ID: 6f3929ac5b09
Revises: 
Create Date: 2025-05-12 23:55:47.427018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f3929ac5b09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_attributes',
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('id_attribute', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('id_unit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_attribute'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['id_unit'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id_project', 'id_attribute')
    )
    op.create_table('projects_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category_images')
    op.drop_table('project_images')
    op.drop_constraint('attributes_ibfk_1', 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'value')
    op.drop_column('attributes', 'id_project')
    op.add_column('category', sa.Column('image', sa.String(length=255), nullable=False))
    op.add_column('cities', sa.Column('image', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('start_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('final_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('payement_date', sa.DATE(), nullable=False))
    op.add_column('orders', sa.Column('start_date', sa.DATE(), nullable=False))
    op.add_column('orders', sa.Column('created_date', sa.DATE(), nullable=False))
    op.add_column('orders', sa.Column('updated_date', sa.DATE(), nullable=False))
    op.alter_column('orders', 'end_date',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'begin_date')
    op.add_column('projects', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('main_image', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('is_done', sa.Boolean(), nullable=False))
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'address')
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.add_column('projects', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('projects', sa.Column('status', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('projects', 'is_done')
    op.drop_column('projects', 'main_image')
    op.drop_column('projects', 'slug')
    op.add_column('orders', sa.Column('begin_date', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('orders', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.alter_column('orders', 'end_date',
               existing_type=sa.DATE(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('orders', 'updated_date')
    op.drop_column('orders', 'created_date')
    op.drop_column('orders', 'start_date')
    op.drop_column('orders', 'payement_date')
    op.drop_column('orders', 'final_price')
    op.drop_column('orders', 'start_price')
    op.drop_column('cities', 'image')
    op.drop_column('category', 'image')
    op.add_column('attributes', sa.Column('id_project', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('attributes', sa.Column('value', mysql.VARCHAR(length=255), nullable=False))
    op.create_foreign_key('attributes_ibfk_1', 'attributes', 'projects', ['id_project'], ['id'])
    op.create_table('project_images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id_project', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], name='project_images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category_images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id_category', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], name='category_images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('projects_images')
    op.drop_table('projects_attributes')
    op.drop_table('units')
    # ### end Alembic commands ###
